<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <Version>3.10.0</Version>
    </PropertyGroup>

    <PropertyGroup Condition="($(RuntimeIdentifier) == '' and $([MSBuild]::IsOSPlatform('Linux'))) or $(RuntimeIdentifier.StartsWith('linux'))">
        <IsLinux>true</IsLinux>
        <DefineConstants>LINUX</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="($(RuntimeIdentifier) == '' and $([MSBuild]::IsOSPlatform('Windows'))) or $(RuntimeIdentifier.StartsWith('win'))">
        <IsWindows>true</IsWindows>
        <DefineConstants>WINDOWS</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="($(RuntimeIdentifier) == '' and $([MSBuild]::IsOSPlatform('OSX'))) or $(RuntimeIdentifier.StartsWith('osx'))">
        <IsMacOS>true</IsMacOS>
        <DefineConstants>MACOS</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Eto.Forms" Version="2.9.0"/>

        <PackageReference Include="SkiaSharp" Version="2.88.8" />
        <PackageReference Include="Samboy063.Tomlet" Version="5.3.1"/>
        <PackageReference Include="Markdig" Version="0.37.0"/>
        <PackageReference Include="Tedd.RandomUtils" Version="1.0.6" />
        <PackageReference Include="LibGit2Sharp" Version="0.31.0"/>

        <ProjectReference Include="..\..\StudioCommunication\StudioCommunication.csproj"/>
        <ProjectReference Include="..\..\external\Featherline\Featherline.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Assets\Icon.ico" LogicalName="Icon.ico"/>
        <EmbeddedResource Include="Assets\Icon.svg" LogicalName="Icon.svg"/>
        <EmbeddedResource Include="Assets\Icon_16x16.png" LogicalName="Icon_16x16.png"/>
        <EmbeddedResource Include="Assets\Icon_32x32.png" LogicalName="Icon_32x32.png"/>
        <EmbeddedResource Include="Assets\Icon_48x48.png" LogicalName="Icon_48x48.png"/>
        <EmbeddedResource Include="Assets\Icon_64x64.png" LogicalName="Icon_64x64.png"/>
        <EmbeddedResource Include="Assets\Icon_128x128.png" LogicalName="Icon_128x128.png"/>
        <EmbeddedResource Include="Assets\Icon_256x256.png" LogicalName="Icon_256x256.png"/>
    </ItemGroup>

    <!-- Windows requires .otf, macOS requires .ttf and GTK doesn't seem to care -->
    <ItemGroup Condition="$(IsMacOS) == 'true'">
        <EmbeddedResource Include="Assets\JetBrainsMono\JetBrainsMonoNL-Light.ttf" LogicalName="JetBrainsMono/JetBrainsMono-Regular"/>
        <EmbeddedResource Include="Assets\JetBrainsMono\JetBrainsMonoNL-Bold.ttf" LogicalName="JetBrainsMono/JetBrainsMono-Bold"/>
        <EmbeddedResource Include="Assets\JetBrainsMono\JetBrainsMonoNL-Italic.ttf" LogicalName="JetBrainsMono/JetBrainsMono-Italic"/>
        <EmbeddedResource Include="Assets\JetBrainsMono\JetBrainsMonoNL-BoldItalic.ttf" LogicalName="JetBrainsMono/JetBrainsMono-BoldItalic"/>
    </ItemGroup>
    <ItemGroup Condition="$(IsMacOS) != 'true'">
        <EmbeddedResource Include="Assets\JetBrainsMono\JetBrainsMonoNL-Light.otf" LogicalName="JetBrainsMono/JetBrainsMono-Regular"/>
        <EmbeddedResource Include="Assets\JetBrainsMono\JetBrainsMonoNL-Bold.otf" LogicalName="JetBrainsMono/JetBrainsMono-Bold"/>
        <EmbeddedResource Include="Assets\JetBrainsMono\JetBrainsMonoNL-Italic.otf" LogicalName="JetBrainsMono/JetBrainsMono-Italic"/>
        <EmbeddedResource Include="Assets\JetBrainsMono\JetBrainsMonoNL-BoldItalic.otf" LogicalName="JetBrainsMono/JetBrainsMono-BoldItalic"/>
    </ItemGroup>

</Project>
