namespace CelesteStudio.Editing;

public struct CommandInfo {
    public string Name;
    public string Description;
    public string Insert;
    
    public static readonly CommandInfo?[] AllCommands = [
        new CommandInfo { Name = "EnforceLegal", Insert = "EnforceLegal" },
        new CommandInfo { Name = "Unsafe", Insert = "Unsafe" },
        new CommandInfo { Name = "Safe", Insert = "Safe" },
        null,
        new CommandInfo { Name = "Read", Insert = "Read, File Name, Starting Line, (Ending Line)" },
        new CommandInfo { Name = "Player", Insert = "Play, Starting Line" },
        null,
        new CommandInfo { Name = "Repeat", Insert = "Repeat 2\n\nEndRepeat" },
        new CommandInfo { Name = "EndRepeat", Insert = "EndRepeat" },
        null,
        new CommandInfo { Name = "Set", Insert = "Set, (Mod).Setting, Value" },
        new CommandInfo { Name = "Invoke", Insert = "Invoke, Entity.Method, Parameter" },
        new CommandInfo { Name = "EvalLua", Insert = "EvalLua, Code" },
        null,
        new CommandInfo { Name = "Press", Insert = "Press, Key1, Key2..." },
        null,
        new CommandInfo { Name = "AnalogMode", Insert = "AnalogMode, Ignore/Circle/Square/Precise" },
        null,
        new CommandInfo { Name = "StunPause", Insert = "StunPause\n\nEndStunPause" },
        new CommandInfo { Name = "EndStunPause", Insert = "EndStunPause" },
        new CommandInfo { Name = "StunPauseMode", Insert = "StunPauseMode, Simulate/Input" },
        null,
        new CommandInfo { Name = "AutoInput", Insert = "AutoInput, 2\n   1,S,N\n  10,O\nStartAutoInput\n\nEndAutoInput" },
        new CommandInfo { Name = "StartAutoInput", Insert = "StartAutoInput" },
        new CommandInfo { Name = "EndAutoInput", Insert = "EndAutoInput" },
        new CommandInfo { Name = "SkipInput", Insert = "SkipInput" },
        null,
        new CommandInfo { Name = "SaveAndQuitReenter", Insert = "SaveAndQuitReenter" },
        null,
        new CommandInfo { Name = "ExportGameInfo", Insert = "ExportGameInfo dump.txt" },
        new CommandInfo { Name = "EndExportGameInfo", Insert = "EndExportGameInfo" },
        null,
        new CommandInfo { Name = "StartRecording", Insert = "StartRecording" },
        new CommandInfo { Name = "StopRecording", Insert = "StopRecording" },
        null,
        new CommandInfo { Name = "Add", Insert = "Add, (input line" },
        new CommandInfo { Name = "Skip", Insert = "Skip" },
        new CommandInfo { Name = "Marker", Insert = "Marker" },
        new CommandInfo { Name = "ExportLibTAS", Insert = "ExportLibTAS Celeste.ltm" },
        new CommandInfo { Name = "EndExportLibTAS", Insert = "EndExportLibTAS" },
        null,
        new CommandInfo { Name = "CompleteInfo", Insert = "CompleteInfo A 1" },
        new CommandInfo { Name = "RecordCount", Insert = "RecordCount: 1" },
        new CommandInfo { Name = "FileTime", Insert = "FileTime:" },
        new CommandInfo { Name = "ChapterTime", Insert = "ChapterTime:" },
        new CommandInfo { Name = "MidwayFileTime", Insert = "MidwayFileTime:" },
        new CommandInfo { Name = "MidwayChapterTime", Insert = "MidwayChapterTime:" },
        null,
        new CommandInfo { Name = "ExitGame", Insert = "ExitGame" },
    ];
}